### ISSUE TITLE
onchanged function ui library error

### ISSUE THREAD

**Issue by ghost** [dawid-scripts/Fluent#18]

**Comment by xxl3rs** [comment]
bozo + ratio + the curse of nile🦉(┬┬﹏┬┬)ᓚᘏᗢಥ_ಥಠ_ಠ༼ つ ◕_◕ ༽つ:-x^.^^^(#｀-_ゝ-)o(￣┰￣*)ゞ( *^-^)ρ(*╯^╰)（＞人＜；）o((>ω< ))o(～￣(OO)￣)ブo(≧口≦)o(╬▔皿▔)╯
