### ISSUE TITLE
Editing keybind seemingly doesn't work

### ISSUE THREAD

**Issue by Compwnter** [dawid-scripts/Fluent#2]
I've tried to change "MinimizeKeybind" to Enum.KeyCode.V but it seemingly hasn't worked
```lua
local Window = Fluent:CreateWindow({
	Title = "",
	SubTitle = "",
	TabWidth = 120,
	Size = UDim2.fromOffset(615, 366),
	Theme = "Dark",
	MinimizeKeybind = Enum.KeyCode.V,
})
```
Sorry in advance if I've misunderstood something!

**Comment by DarksGitHub** [comment]
@Compwnter it doesn't look like the library supports the MinimizeKeybind part at all.

**Comment by dawid-scripts** [comment]
added MinimizeKey argument, used when theres no MinimizeKeybind
