### ISSUE TITLE
spams, "Mesh is not a valid member of Part "Body""

### ISSUE THREAD

**Issue by vvvvvbyte** [dawid-scripts/Fluent#39]
i have no idea why this happens, mesh is a part of body and this only happens when your characters camera is moved (i think)

below is a video of the errors happening and another is an image of mesh being a valid member

(also this happened with my script and the example script)

https://youtu.be/x_7IEg1g45k (video)

![image](https://github.com/dawid-scripts/Fluent/assets/151686323/8ad62aa5-df9a-4a37-9580-71135844a5eb)

**Comment by ActualMasterOogway** [comment]
What executor are you using?

EDIT: Looks like you are using Celery, Celery is currently in early early access and is not intented to be used for use. It was only a test to see if the injection part works. This is an issue on Celery's end

**Comment by vvvvvbyte** [comment]
i used multiple different executors and they all did the same, i talked to dawid and he said just disable the blur
